# Site settings
encoding: utf-8
title: 执着的小浮云
description: 小浮云的工作、生活随笔
baseurl: "https://willofcloud.github.io/myblog/"
# baseurl: ''
github_username:  WillOfCloud
paginate: 8
paginate_path: "/page:num"
#footer_twitter: "Twitter"
#footer_twitter_site: "https://twitter.com/cody19910828"
#footer_github: "GitHub"
#footer_resume: "简历"
#footer_resume_site: "https://cody1991.github.io/aboutme/index.html"
footer_template: "博客模板"
footer_template_site: "cody1991/cody1991.github.io"
port: 8070
gems: [jekyll-paginate]
